// Mangled symbol names from the survev client bundle.
//
// AUTO-GENERATED by derive_mangled.py from rv39I73V_formatted.js.
// Do not edit by hand — re-run `python derive_mangled.py` after each
// `python fetch_survev_js.py`.
//
// Survev ships its client bundle re-mangled on each deploy: readable
// TypeScript field names get renamed to short opaque identifiers like
// `qJm`, `TXaUHs`, etc., and those names change every build. This file
// is the single source of truth that maps semantic names (what each
// field MEANS) to mangled names (what it's CALLED in the current bundle).
// inject.js reads every name through this dictionary.
//
// The anchors used to re-derive each name are documented in derive_mangled.py.

window.__SURVEV_MANGLED__ = {
  // ---- Player class (`er` in bundle) ----
  // Anchor: class declaring `bodySprite`, `helmetSprite`, `meleeSprite`,
  // `footLSprite`, `handLContainer`, etc. as own fields.
  player: {
    netData:      'bjUNH',
    localData:    'dpKj',
    pos:          'Swy',
    dir:          'MwORbI',
    posAlt:       'KQY',
    dirAlt:       'QCgHU',
    action:       'SlHhzP',
  },

  // ---- Player.netData (the sub-object named by player.netData above) ----
  netData: {
    activeWeapon: 'YRQ',
    dead:         'elD',
    downed:       'kuwVe',
    scale:        'PHuK',
    animType:     'JXaTNr',
    animSeq:      'XYAmIb',
    actionType:   'Mcan',
    frozen:       'nGJqb',
    hasteType:    'KXtUm',
    perks:        'sZpxj',
  },

  // ---- Player.localData (the sub-object named by player.localData above) ----
  localData: {
    zoom:       'ueYRQD',
    boost:      'ldGzU',
    curWeapIdx: 'mit',
    weapons:    'BaVl',
  },

  // ---- Game class (`Rr` in bundle) ----
  game: {
    localPlayer: 'lmxTi',
    roster:      'qjoB',
    inputBinds:  'DBpYw',
    camera:      'pTCE',
  },

  // ---- Camera class (`ct` in bundle) ----
  // `interpWindow` is seconds-per-server-update: the game overwrites it with
  // the RAW last packet inter-arrival on every update, and every entity
  // divides its `posInterpTicker` by it to get a 0..1 lerp fraction. inject.js
  // replaces it with a jitter-buffered estimate — see the netcode smoothing
  // block there.
  camera: {
    interpWindow:  'LhhGRR',
    interpEnabled: 'AaG',
  },

  // ---- Pool class (entity pools) ----
  pool: {
    getAll: 'SdnQ',
  },

  // ---- Rr-constructor positional-param assignments ----
  // (used to seed Object.prototype setter traps so we can capture the
  // Game instance on first construction — see inject.js)
  seedNames: [
    'rOPb', 'VvWyR', 'ZIlpkD', 'Qaon', 'MjNY',
    'DBpYw', 'IRvt', 'VZCyQ', 'wfSEiv',
  ],
};
