// Mangled symbol names from the survev client bundle.
//
// AUTO-GENERATED by derive_mangled.py from _ExrH9OQ_formatted.js.
// Do not edit by hand — re-run `python derive_mangled.py` after each
// `python fetch_survev_js.py`.
//
// Survev ships its client bundle re-mangled on each deploy: readable
// TypeScript field names get renamed to short opaque identifiers like
// `qJm`, `TXaUHs`, etc., and those names change every build. This file
// is the single source of truth that maps semantic names (what each
// field MEANS) to mangled names (what it's CALLED in the current bundle).
// inject.js reads every name through this dictionary.
//
// The anchors used to re-derive each name are documented in derive_mangled.py.

window.__SURVEV_MANGLED__ = {
  // ---- Player class (`er` in bundle) ----
  // Anchor: class declaring `bodySprite`, `helmetSprite`, `meleeSprite`,
  // `footLSprite`, `handLContainer`, etc. as own fields.
  player: {
    netData:   'qJm',
    localData: 'TXaUHs',
    pos:       'lxf',
    dir:       'vNoOA',
    posAlt:    'Iyc',
  },

  // ---- Player.netData (the sub-object named by player.netData above) ----
  netData: {
    activeWeapon: 'ztD',
    dead:         'ZyVG',
    downed:       'qqS',
  },

  // ---- Player.localData (the sub-object named by player.localData above) ----
  localData: {
    zoom:       'GGcNO',
    curWeapIdx: 'GDBm',
    weapons:    'sRJ',
  },

  // ---- Game class (`Rr` in bundle) ----
  game: {
    localPlayer: 'MGSQS',
    roster:      'gHU',
    inputBinds:  'ePAMCZ',
  },

  // ---- Pool class (entity pools) ----
  pool: {
    getAll: 'MXR',
  },

  // ---- Rr-constructor positional-param assignments ----
  // (used to seed Object.prototype setter traps so we can capture the
  // Game instance on first construction — see inject.js)
  seedNames: [
    'EFEvjn', 'oJm', 'lmq', 'tpNp', 'hfF',
    'ePAMCZ', 'ZSKPkV', 'FjamQN', 'HNiaBM',
  ],
};
