// Mangled symbol names from the survev client bundle.
//
// AUTO-GENERATED by derive_mangled.py from LmJyYjzB_formatted.js.
// Do not edit by hand — re-run `python derive_mangled.py` after each
// `python fetch_survev_js.py`.
//
// Survev ships its client bundle re-mangled on each deploy: readable
// TypeScript field names get renamed to short opaque identifiers like
// `qJm`, `TXaUHs`, etc., and those names change every build. This file
// is the single source of truth that maps semantic names (what each
// field MEANS) to mangled names (what it's CALLED in the current bundle).
// inject.js reads every name through this dictionary.
//
// The anchors used to re-derive each name are documented in derive_mangled.py.

window.__SURVEV_MANGLED__ = {
  // ---- Player class (`er` in bundle) ----
  // Anchor: class declaring `bodySprite`, `helmetSprite`, `meleeSprite`,
  // `footLSprite`, `handLContainer`, etc. as own fields.
  player: {
    netData:      'ADIAG',
    localData:    'NPBn',
    pos:          'vQHh',
    dir:          'eGczcU',
    posAlt:       'pVwWl',
    dirAlt:       'WNYLHR',
  },

  // ---- Player.netData (the sub-object named by player.netData above) ----
  netData: {
    activeWeapon: 'JJTyLg',
    dead:         'PjgTvG',
    downed:       'vqjzVe',
    scale:        'OpFW',
  },

  // ---- Player.localData (the sub-object named by player.localData above) ----
  localData: {
    zoom:       'kqMZFT',
    curWeapIdx: 'WMV',
    weapons:    'FGb',
  },

  // ---- Game class (`Rr` in bundle) ----
  game: {
    localPlayer: 'Lwy',
    roster:      'zpETX',
    inputBinds:  'Nihlid',
    camera:      'HXc',
  },

  // ---- Camera class (`ct` in bundle) ----
  // `interpWindow` is seconds-per-server-update: the game overwrites it with
  // the RAW last packet inter-arrival on every update, and every entity
  // divides its `posInterpTicker` by it to get a 0..1 lerp fraction. inject.js
  // replaces it with a jitter-buffered estimate — see the netcode smoothing
  // block there.
  camera: {
    interpWindow:  'pOs',
    interpEnabled: 'xxVIlr',
  },

  // ---- Pool class (entity pools) ----
  pool: {
    getAll: 'JNmcya',
  },

  // ---- Rr-constructor positional-param assignments ----
  // (used to seed Object.prototype setter traps so we can capture the
  // Game instance on first construction — see inject.js)
  seedNames: [
    'Zpxj', 'bDIH', 'zgKYvJ', 'zcAncX', 'GRFZiC',
    'Nihlid', 'zaaBSL', 'Pvab', 'JfKCF',
  ],
};
