// Mangled symbol names from every supported client bundle.
//
// AUTO-GENERATED by update_mangled.py. Do not edit by hand — re-run
// `python update_mangled.py` to refetch the current bundles and re-derive.
//
// Both sites ship the same game from two separately-built, separately-
// mangled clients: readable TypeScript/JS field names get renamed to short
// opaque identifiers like `qJm`, `TXaUHs`, `De`, and those names change on
// every deploy. (surviv.io leaves a few of them under their real names, e.g.
// `pos` — that's not a bug in the derivation, it's what that build calls the
// field.) This file is the single source of truth mapping semantic names
// (what each field MEANS) to the mangled name each build gives it.
//
// inject.js reads every name through the dictionary picked for the current
// hostname at the bottom of this file, so nothing else in the extension has to
// know which site it is running on.
//
// The anchors used to re-derive each name are documented in update_mangled.py.
//
// Two groups per site are NOT derived from the bundle — `antiDetect` and
// `capture` are standing per-site policy, and they live in SITE_POLICY in
// update_mangled.py. Change them there, not here.

Object.defineProperty(window, '__SURVEV_MANGLED_SITES__', {
  configurable: true, enumerable: false, writable: true,
  value: {
  // =====================================================================
  // survev.io — derived from LmJyYjzB_formatted.js
  // =====================================================================
  'survev.io': {
    // ---- Player class ----
    // Anchor: class declaring `bodySprite`, `helmetSprite`, `meleeSprite`,
    // `footLSprite`, `handLContainer`, etc. as own fields.
    player: {
      netData:      'ADIAG',
      localData:    'NPBn',
      pos:          'vQHh',
      dir:          'eGczcU',
      posAlt:       'pVwWl',
      dirAlt:       'WNYLHR',
    },

    // ---- Player.netData (the sub-object named by player.netData above) ----
    netData: {
      activeWeapon: 'JJTyLg',
      dead:         'PjgTvG',
      downed:       'vqjzVe',
      scale:        'OpFW',
    },

    // ---- Player.localData (the sub-object named by player.localData above) ----
    localData: {
      zoom:       'kqMZFT',
      curWeapIdx: 'WMV',
      weapons:    'FGb',
    },

    // ---- Game class ----
    game: {
      localPlayer: 'Lwy',
      roster:      'zpETX',
      inputBinds:  'Nihlid',
      camera:      'HXc',
    },

    // ---- Roster / player-barn class (named by game.roster above) ----
    // `playerPool` holds the streamed-in Player entities — that's where
    // enemies are. `getPlayerInfo(id)` returns name/team/group for one id.
    roster: {
      playerPool:    'playerPool',
      getPlayerInfo: 'getPlayerInfo',
    },

    // ---- Camera class ----
    // `interpWindow` is seconds-per-server-update: the game overwrites it with
    // the RAW last packet inter-arrival on every update, and every entity
    // divides its `posInterpTicker` by it to get a 0..1 lerp fraction.
    // inject.js replaces it with a jitter-buffered estimate — see the netcode
    // smoothing block there.
    camera: {
      interpWindow:  'pOs',
      interpEnabled: 'xxVIlr',
    },

    // ---- Pool class (entity pools) ----
    pool: {
      getAll: 'JNmcya',
    },

    // ---- Client-side extension detection ----
    // NOT derived — standing policy, see SITE_POLICY in update_mangled.py.
    // surviv.io's client scans every 30 frames for sprites below an alpha
    // threshold and closes its own WebSocket when it finds one; the hook
    // neutralises that predicate before the bundle evaluates.
    antiDetect: { webpackChunkHook: false },

    // ---- Game capture strategy ----
    // NOT derived — standing policy, see SITE_POLICY in update_mangled.py.
    // `protoTrap: false` means the Game is captured by the bind hook alone
    // and `seedNames` below goes unused. It is kept either way: it costs
    // nothing, and it is the cheapest way to re-enable the trap if the bind
    // hook ever regresses on that build.
    capture: { protoTrap: true },

    // ---- Game-constructor positional-param assignments ----
    // (used to seed Object.prototype setter traps so we can capture the
    // Game instance on first construction — see inject.js)
    seedNames: [
      'Zpxj', 'bDIH', 'zgKYvJ', 'zcAncX', 'GRFZiC',
      'Nihlid', 'zaaBSL', 'Pvab', 'JfKCF',
    ],
  },

  // =====================================================================
  // surviv.io — derived from app.e1c5249a_formatted.js
  // =====================================================================
  'surviv.io': {
    // ---- Player class ----
    // Anchor: class declaring `bodySprite`, `helmetSprite`, `meleeSprite`,
    // `footLSprite`, `handLContainer`, etc. as own fields.
    player: {
      netData:      'De',
      localData:    'tt',
      pos:          'pos',
      dir:          'dir',
      posAlt:       'visualPos',
      dirAlt:       'visualDir',
    },

    // ---- Player.netData (the sub-object named by player.netData above) ----
    netData: {
      activeWeapon: 'H',
      dead:         'K',
      downed:       'J',
      scale:        'le',
    },

    // ---- Player.localData (the sub-object named by player.localData above) ----
    localData: {
      zoom:       'je',
      curWeapIdx: 'rt',
      weapons:    'et',
    },

    // ---- Game class ----
    game: {
      localPlayer: 'Je',
      roster:      'Se',
      inputBinds:  'ut',
      camera:      'zt',
    },

    // ---- Roster / player-barn class (named by game.roster above) ----
    // `playerPool` holds the streamed-in Player entities — that's where
    // enemies are. `getPlayerInfo(id)` returns name/team/group for one id.
    roster: {
      playerPool:    'Pe',
      getPlayerInfo: 'Ze',
    },

    // ---- Camera class ----
    // `interpWindow` is seconds-per-server-update: the game overwrites it with
    // the RAW last packet inter-arrival on every update, and every entity
    // divides its `posInterpTicker` by it to get a 0..1 lerp fraction.
    // inject.js replaces it with a jitter-buffered estimate — see the netcode
    // smoothing block there.
    camera: {
      interpWindow:  'Fe',
      interpEnabled: 'Le',
    },

    // ---- Pool class (entity pools) ----
    pool: {
      getAll: 'ge',
    },

    // ---- Client-side extension detection ----
    // NOT derived — standing policy, see SITE_POLICY in update_mangled.py.
    // surviv.io's client scans every 30 frames for sprites below an alpha
    // threshold and closes its own WebSocket when it finds one; the hook
    // neutralises that predicate before the bundle evaluates.
    antiDetect: { webpackChunkHook: true },

    // ---- Game capture strategy ----
    // NOT derived — standing policy, see SITE_POLICY in update_mangled.py.
    // `protoTrap: false` means the Game is captured by the bind hook alone
    // and `seedNames` below goes unused. It is kept either way: it costs
    // nothing, and it is the cheapest way to re-enable the trap if the bind
    // hook ever regresses on that build.
    capture: { protoTrap: false },

    // ---- Game-constructor positional-param assignments ----
    // (used to seed Object.prototype setter traps so we can capture the
    // Game instance on first construction — see inject.js)
    seedNames: [
      'lt', 'ct', 'ht', 'ut', 'dt',
    ],
  },
},
});

// Pick the dictionary for whatever host this content script was injected into.
// Subdomains count (`ptr.survev.io` is the same build as `survev.io`), so we
// match on an exact hostname or a dot-suffix of one — never a bare substring,
// which would let e.g. `notsurviv.io.example.com` through.
(() => {
  const host = String(location.hostname || '').toLowerCase();
  const sites = window.__SURVEV_MANGLED_SITES__;
  let matched = null;
  for (const site of Object.keys(sites)) {
    if (host === site || host.endsWith('.' + site)) { matched = site; break; }
  }
  // Non-enumerable: keeps us out of Object.keys(window), which surviv.io's
  // `ki()` walks. Still readable by name from inject.js and the console.
  const hide = (k, v) => Object.defineProperty(window, k, {
    configurable: true, enumerable: false, writable: true, value: v,
  });
  hide('__SURVEV_MANGLED_SITE__', matched);
  hide('__SURVEV_MANGLED__', matched ? sites[matched] : null);
})();
