// Mangled symbol names from the survev client bundle.
//
// AUTO-GENERATED by derive_mangled.py from Dzch6shQ_formatted.js.
// Do not edit by hand — re-run `python derive_mangled.py` after each
// `python fetch_survev_js.py`.
//
// Survev ships its client bundle re-mangled on each deploy: readable
// TypeScript field names get renamed to short opaque identifiers like
// `qJm`, `TXaUHs`, etc., and those names change every build. This file
// is the single source of truth that maps semantic names (what each
// field MEANS) to mangled names (what it's CALLED in the current bundle).
// inject.js reads every name through this dictionary.
//
// The anchors used to re-derive each name are documented in derive_mangled.py.

window.__SURVEV_MANGLED__ = {
  // ---- Player class (`er` in bundle) ----
  // Anchor: class declaring `bodySprite`, `helmetSprite`, `meleeSprite`,
  // `footLSprite`, `handLContainer`, etc. as own fields.
  player: {
    netData:      'rUNX',
    localData:    'HYWCaI',
    pos:          'hgUS',
    dir:          'Npmmxm',
    posAlt:       'lnPgk',
    dirAlt:       'Mpt',
  },

  // ---- Player.netData (the sub-object named by player.netData above) ----
  netData: {
    activeWeapon: 'PyX',
    dead:         'ZvC',
    downed:       'GxpD',
    scale:        'MQCs',
  },

  // ---- Player.localData (the sub-object named by player.localData above) ----
  localData: {
    zoom:       'XgYNX',
    curWeapIdx: 'sEntIp',
    weapons:    'tcS',
  },

  // ---- Game class (`Rr` in bundle) ----
  game: {
    localPlayer: 'iiBVMz',
    roster:      'KHPVB',
    inputBinds:  'HPqrv',
    camera:      'VEdOEn',
  },

  // ---- Camera class (`ct` in bundle) ----
  // `interpWindow` is seconds-per-server-update: the game overwrites it with
  // the RAW last packet inter-arrival on every update, and every entity
  // divides its `posInterpTicker` by it to get a 0..1 lerp fraction. inject.js
  // replaces it with a jitter-buffered estimate — see the netcode smoothing
  // block there.
  camera: {
    interpWindow:  'jUpjUA',
    interpEnabled: 'heulkU',
  },

  // ---- Pool class (entity pools) ----
  pool: {
    getAll: 'qHgS',
  },

  // ---- Rr-constructor positional-param assignments ----
  // (used to seed Object.prototype setter traps so we can capture the
  // Game instance on first construction — see inject.js)
  seedNames: [
    'zLZdz', 'BjM', 'fnb', 'mnL', 'TKs',
    'HPqrv', 'DfOdHt', 'CrRSKN', 'JyfCWX',
  ],
};
